<a href="https://colab.research.google.com/github/SShresth7272/Python-Code/blob/main/Groupby_and_Aggregation_in_Pandas_PracticeSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sales_data_sample.csv to sales_data_sample.csv

In [ ]:
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['sales_data_sample.csv']))

In [ ]:
df.shape

(2823, 25)

In [ ]:
df.head(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
5,10168,36,96.66,1,3479.76,10/28/2003 0:00,Shipped,4,10,2003,...,9408 Furth Circle,NaN,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium
6,10180,29,86.13,9,2497.77,11/11/2003 0:00,Shipped,4,11,2003,...,"184, chausse de Tournai",NaN,Lille,NaN,59000,France,EMEA,Rance,Martine,Small
7,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",NaN,Bergen,NaN,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
8,10201,22,98.57,2,2168.54,12/01/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,NaN,San Francisco,CA,NaN,USA,NaN,Murphy,Julie,Small
9,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",NaN,Paris,NaN,75016,France,EMEA,Perrier,Dominique,Medium

In [ ]:
df.tail(10)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2813,10293,32,60.06,1,1921.92,09/09/2004 0:00,Shipped,3,9,2004,...,Via Monte Bianco 34,NaN,Torino,NaN,10100,Italy,EMEA,Accorti,Paolo,Small
2814,10306,35,59.51,6,2082.85,10/14/2004 0:00,Shipped,4,10,2004,...,Fauntleroy Circus,NaN,Manchester,NaN,EC2 5NT,UK,EMEA,Ashworth,Victoria,Small
2815,10315,40,55.69,5,2227.60,10/29/2004 0:00,Shipped,4,10,2004,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
2816,10327,37,86.74,4,3209.38,11/10/2004 0:00,Resolved,4,11,2004,...,Vinb'ltet 34,NaN,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Medium
2817,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,NaN,Hernandez,Maria,Medium
2818,10350,20,100.00,15,2244.40,12/02/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,03/01/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,05/06/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
df.groupby('SALES').agg('sum')

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
SALES,,,,,,,,,,,,,,,,,,,,,
482.13,10425,11,43.83,6,5/31/2005 0:00,In Process,2,5,2005,Trucks and Buses,...,"67, rue des Cinquante Otages",0,Nantes,0,44000,France,EMEA,Labrune,Janine,Small
541.14,10407,6,90.19,3,4/22/2005 0:00,On Hold,2,4,2005,Vintage Cars,...,3086 Ingle Ln.,0,San Jose,CA,94217,USA,0,Frick,Sue,Small
553.95,10408,15,36.93,1,4/22/2005 0:00,Shipped,2,4,2005,Vintage Cars,...,2-2-8 Roppongi,0,Minato-ku,Tokyo,106-0032,Japan,Japan,Shimamura,Akiko,Small
577.60,10280,20,28.88,12,8/17/2004 0:00,Shipped,3,8,2004,Vintage Cars,...,Via Monte Bianco 34,0,Torino,0,10100,Italy,EMEA,Accorti,Paolo,Small
640.05,10419,15,42.67,7,5/17/2005 0:00,Shipped,2,5,2005,Classic Cars,...,Geislweg 14,0,Salzburg,0,5020,Austria,EMEA,Pipps,Georg,Small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11886.60,10403,66,100.00,9,04/08/2005 0:00,Shipped,2,4,2005,Motorcycles,...,Berkeley Gardens 12 Brewery,0,Liverpool,0,WX1 6LT,UK,EMEA,Devon,Elizabeth,Large
11887.80,10412,60,100.00,9,05/03/2005 0:00,Shipped,2,5,2005,Classic Cars,...,"C/ Moralzarzal, 86",0,Madrid,0,28034,Spain,EMEA,Freyre,Diego,Large
12001.00,10424,50,100.00,6,5/31/2005 0:00,In Process,2,5,2005,Classic Cars,...,"C/ Moralzarzal, 86",0,Madrid,0,28034,Spain,EMEA,Freyre,Diego,Large
12536.50,10322,50,100.00,6,11/04/2004 0:00,Shipped,4,11,2004,Vintage Cars,...,2304 Long Airport Avenue,0,Nashua,NH,62005,USA,0,Young,Valarie,Large
14082.80,10407,76,100.00,2,4/22/2005 0:00,On Hold,2,4,2005,Vintage Cars,...,3086 Ingle Ln.,0,San Jose,CA,94217,USA,0,Frick,Sue,Large

In [ ]:
df.groupby('PRICEEACH').agg('min', numeric_only=True)

,ORDERNUMBER,QUANTITYORDERED,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
PRICEEACH,,,,,,,,
26.88,10420,45,1,1209.60,2,5,2005,33
27.22,10162,37,5,1007.14,4,10,2003,33
28.29,10195,32,7,905.28,4,11,2003,35
28.88,10280,20,12,577.60,3,8,2004,33
29.21,10193,26,6,759.46,1,3,2003,33
...,...,...,...,...,...,...,...,...
99.69,10339,29,14,2891.01,4,11,2004,65
99.72,10210,26,14,2592.72,1,1,2004,99
99.82,10122,25,7,2495.50,1,2,2003,117
99.91,10107,39,5,3896.49,1,2,2003,118
100.00,10100,6,1,785.64,1,1,2003,33

In [ ]:
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
df.groupby('CITY')['SALES'].agg(['sum', 'mean', 'max'])

                    sum         mean       max
CITY
Aaarhus       100595.55  3725.761111   7975.44
Allentown     122138.14  3939.940000   7962.24
Barcelona      78411.86  3409.211304   6482.85
Bergamo       137955.72  2874.077500   5279.40
Bergen        111640.28  3849.664828   8714.70
...                 ...          ...       ...
Toulouse       70488.44  3524.422000   8331.61
Tsawassen      74634.85  2870.571154   5795.54
Vancouver      75238.92  3419.950909   9064.89
Versailles     64834.32  3601.906667  10172.70
White Plains   85555.99  3290.615000   7620.50

[73 rows x 3 columns]

In [ ]:
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
df.info()  df.groupby('PRICEEACH').agg({'B': ['min', 'max'], 'C': 'sum'})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

In [ ]:
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,05/07/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,07/01/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
df.groupby('PRICEEACH').agg({'QUANTITYORDERED': ['min', 'max'], 'SALES': 'sum'})

          QUANTITYORDERED           SALES
                      min max         sum
PRICEEACH
26.88                  45  45     1209.60
27.22                  37  37     1007.14
28.29                  32  32      905.28
28.88                  20  20      577.60
29.21                  26  42     1986.28
...                   ...  ..         ...
99.69                  29  29     2891.01
99.72                  26  26     2592.72
99.82                  25  37     6188.84
99.91                  39  39     3896.49
100.00                  6  76  6338042.06

[1016 rows x 3 columns]